$env:WC_KEY = ''
$env:WC_SECRET = ''
$env:DB_USER = ''
$env:DB_PASSWORD = ''
$env:DB_SERVER = ''
$env:DB_NAME = ''
$env:SELPATH = ''
$env:SITE_URL = ''
$env:COUPON = 'test_coupon'
$env:PORT = ''
$env:Host = ''

